export const AUTH_SUCCESS = "AUTH_SUCCESS"
export const AUTH_ERROR = "AUTH_ERROR"
export const USER_LOADED = "USER_LOADED"
export const LOGOUT = "LOGOUT"

export const GET_ALL_USERS = "GET_ALL_USERS"
export const USER_OPERATION_ERROR = "USER_OPERATION_ERROR"
export const USER_OPERATION = "USER_OPERATION"

export const GET_ALL_BOOKS = "GET_ALL_BOOKS"
export const BOOK_OPERATION = "BOOK_OPERATION"
export const BOOK_OPERATION_ERROR = "BOOK_OPERATION_ERROR"